ms-python.python
ms-python.debugpy
njpwerner.autodocstring
ms-toolsai.jupyter
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-slideshow
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.jupyter-keymap
vscode-icons-team.vscode-icons
sbenp.prettier-vscode
eamodio.gitlens
posit.air-vscode
posit.shiny
quarto.quarto
meta.pyrefly
charliermarsh.ruff
posit.shinyuieditor
hediet.vscode-drawio
posit.publisher